version: "2"
services:
  mysql:
      container_name: pie_mysql_dev
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: nest
        MYSQL_USER: test
        MYSQL_PASSWORD: test
      ports:
        - "3308:3306"
      expose:
        - "3306"
      volumes:
          - ./dump_dev.sql:/sql/dump_dev.sql
      networks:
        pie_local_pie-local:
          ipv4_address: 10.5.0.100
networks:
  pie_local_pie-local:
   external: true
 
